### ISSUE TITLE
swift 2.3 update

### ISSUE THREAD

**Issue by userna** [zenangst/Hue#23]
![image](https://cloud.githubusercontent.com/assets/3657187/17000733/cc87be70-4e78-11e6-9525-695cf083c111.png)
UIImage+Hue
ln21,47,48

**Comment by zenangst** [comment]
Hey @userna, we don't have a Swift 2.3 version of `Hue`. Seeing as Apple will drop support for that version in the next Xcode, we felt that it was a "bad" investment for us, but if you want, we can make a branch that you can make a PR towards to make it support Swift 2.3. However, this issue is a bit old so I'm just gonna close it. Keep us posted if you are still using Swift 2.3 and would like to use Hue.
